NienLuan2/Models/HOTRO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTRO
    {
        public int MA_HT { get; set; }
        public string HoTen_HT { get; set; }
        public string Cau_Hoi { get; set; }
        public string SDT_HT { get; set; }
        public string Email_HT { get; set; }
        public string MA_TT_HT { get; set; }
    
        public virtual TRANGTHAI_HOTRO TRANGTHAI_HOTRO { get; set; }
    }
}

NienLuan2/Controllers/HoTroController.cs
using NienLuan2.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static System.Collections.Specialized.BitVector32;

namespace NienLuan2.Controllers
{
    public class HoTroController : Controller
    {
        NL2_QLVAEntities1 db = new NL2_QLVAEntities1();
        // GET: HoTro
        public ActionResult ListHT(string searchString, int? error, int page = 1, int pageSize = 10)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                ViewBag.tt = new SelectList(db.TRANGTHAI_HOTRO.OrderBy(x => x.Ten_TT_HT), "MA_TT_HT", "Ten_TT_HT");
                var listHoTro = from s in db.HOTROes select s;

                IEnumerable<HOTRO> model = db.HOTROes;


                return View(model.OrderByDescending(x => x.TRANGTHAI_HOTRO.MA_TT_HT).ToPagedList(page, pageSize));
            }

            else
            {
                ViewBag.tt = new SelectList(db.TRANGTHAI_HOTRO.OrderBy(x => x.Ten_TT_HT), "MA_TT_HT", "Ten_TT_HT");
                var listHoTro = from s in db.HOTROes select s;

                IEnumerable<HOTRO> model = db.HOTROes.Where(ht => ht.SDT_HT.Contains(searchString));
                ViewBag.SearchString = searchString;

                return View(model.OrderByDescending(x => x.TRANGTHAI_HOTRO.MA_TT_HT).ToPagedList(page, pageSize));
            }
           
            
        }

        public ActionResult xoa_HT1(int? id)
        {
            HOTRO hotro = db.HOTROes.SingleOrDefault(s => s.MA_HT == id);
            db.HOTROes.Remove(hotro);
            db.SaveChanges();
            return RedirectToAction("ListHT");
        }
        
        [HttpGet]
        public ActionResult EditTTHT(string id)
        {
            try
            {
                int idInt = Convert.ToInt32(id);
                HOTRO hotro = db.HOTROes.SingleOrDefault(ht => ht.MA_HT == idInt);
                if (hotro.MA_TT_HT == "01")
                    hotro.MA_TT_HT = "02";
                else
                    hotro.MA_TT_HT = "01";
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);  
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

NienLuan2/Views/HoTro/ListHT.cshtml
@model PagedList.IPagedList<NienLuan2.Models.HOTRO>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />
@{
    ViewBag.Title = "ListHT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>  
            <b>HỖ TRỢ</b>
            @using (Html.BeginForm("ListHT", "HoTro", FormMethod.Get, new { @class = "pull-right d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" }))
            {
                <div class="input-group">
                    <input type="text" name="searchString" value="@ViewBag.SearchString" class="form-control" placeholder="Nhập số điện thoại cần tìm..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            }
        </div>
        <input type="hidden" class="TonTaiMa" value="@ViewBag.Loi" />
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" cellspacing="0">
                    <tr>
                        <th>
                            Số thứ tự
                        </th>
                        <th>
                            Họ tên
                        </th>
                        <th>
                            Số điện thoại
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Câu hỏi
                        </th>
                        <th>
                            Trạng thái
                        </th>
                        <th>
                            Thao tác
                        </th>
                    </tr>
                   @{
                       int count = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @count
                            @{
                                count++;
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HoTen_HT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SDT_HT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email_HT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cau_Hoi)
                        </td>
                        <td>
                            @{  string tt;
                                tt = item.MA_TT_HT;
                                if (tt == "01")
                                {
                                    <label class="item  btn btn-success btn-sm" name="MA_TT_HT" value="01">Đã phản hồi</label>
                                }
                                else
                                { <label class="item  btn btn-danger btn-sm" name="MA_TT_HT" value="02">Chưa phản hồi</label>}
                            }
                        </td>
                        <td>
                            <button class="item btn_Sua btn btn-success btn-sm" onclick="EditTTHT('@item.MA_HT')">

                                <i class="fas fa-edit"></i>
                            </button>|
                            <a class="item btn_Sua btn btn-danger btn-sm" onclick="return confirm('Bạn chắc chắn muốn xóa?');" href="@Url.Action("xoa_HT1", new { id = item.MA_HT })">


                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                                }
                </table>
                @Html.PagedListPager(Model, page => Url.Action("ListHT", new { page, @searchString = @ViewBag.SearchString }))
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script type="text/javascript">
        
        function EditTTHT(id) {
            $.ajax({
                url: "/HoTro/EditTTHT/" + id,
                typr: "GET",
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                success: function (response) {
                    if (response == true)
                    location.reload();
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
            return false;
        }
</script>
}